In [1]:
import sklearn

In [2]:
# 버전확인
sklearn.__version__

'0.24.1'

In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier # 분류용 데이터에 사용
# from sklearn.tree import DecisionTreeRegressor # 회귀용 데이터에 사용
from sklearn.model_selection import train_test_split

In [4]:
import pandas as pd

In [5]:
iris = load_iris() # shift+tab 하면 뭐 볼 수 있음

In [6]:
type(iris)  # 딕셔너리같아 보였지만 아님. bunch라는 어쩌구임. 그래도 딕셔너리처럼 쓸 수 있음

sklearn.utils.Bunch

In [7]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [8]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [12]:
iris = load_iris(as_frame = True)

In [13]:
type(iris)

sklearn.utils.Bunch

In [14]:
iris # as_frame = True 로 했더니 형태가 조금 변함. 데이터프레임 형태로 나오게 됨.

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [15]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [16]:
iris_df = iris['data']
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [17]:
iris_df['target'] = iris['target']

In [18]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [19]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [20]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [21]:
# test_size = 데이터를 몇% 쓸것인지. test랑 train이랑 합해서 100
# random_state = 이거 못들음
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2, 
                                                    random_state=0)  #*이 하나면 리스트형태로 전달. 그래서 어레이 여러개가 올 수 있다.
                                                                     #**이렇게 두개면 딕셔너리형태로 전달

In [22]:
x_train, x_test, y_train, y_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
 137                6.4               3.1                5.5               1.8   
 84                 5.4               3.0                4.5               1.5   
 27                 5.2               3.5                1.5               0.2   
 127                6.1               3.0                4.9               1.8   
 132                6.4               2.8                5.6               2.2   
 ..                 ...               ...                ...               ...   
 9                  4.9               3.1                1.5               0.1   
 103                6.3               2.9                5.6               1.8   
 67                 5.8               2.7                4.1               1.0   
 117                7.7               3.8                6.7               2.2   
 47                 4.6               3.2                1.4               0.2   
 
      target  

In [23]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
Name: target, dtype: int32

In [24]:
type(x_train)

pandas.core.frame.DataFrame

In [25]:
df_clf = DecisionTreeClassifier(random_state=11)

In [26]:
df_clf

DecisionTreeClassifier(random_state=11)

In [27]:
df_clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=11)

In [28]:
# predict : 답을 안주고 예측시켜보기
pred = df_clf.predict(x_test)

In [29]:
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [30]:
y_test

114    2
62     1
33     0
107    2
7      0
100    2
40     0
86     1
76     1
71     1
134    2
51     1
73     1
54     1
63     1
37     0
78     1
90     1
45     0
16     0
121    2
66     1
24     0
8      0
126    2
22     0
44     0
97     1
93     1
26     0
Name: target, dtype: int32

In [31]:
from sklearn.metrics import accuracy_score # 평가와 관련된 것들이 들어있음. 

In [32]:
accuracy_score(y_test, pred)

1.0

In [33]:
# random_state = 0으로 해보기
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2) 

In [34]:
x_train, x_test, y_train, y_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
 18                 5.7               3.8                1.7               0.3   
 26                 5.0               3.4                1.6               0.4   
 56                 6.3               3.3                4.7               1.6   
 25                 5.0               3.0                1.6               0.2   
 52                 6.9               3.1                4.9               1.5   
 ..                 ...               ...                ...               ...   
 123                6.3               2.7                4.9               1.8   
 128                6.4               2.8                5.6               2.1   
 85                 6.0               3.4                4.5               1.6   
 50                 7.0               3.2                4.7               1.4   
 76                 6.8               2.8                4.8               1.4   
 
      target  

In [35]:
y_test

23     0
48     0
0      0
36     0
124    2
9      0
99     1
3      0
38     0
28     0
98     1
132    2
65     1
79     1
43     0
41     0
27     0
139    2
107    2
114    2
6      0
78     1
102    2
29     0
116    2
80     1
72     1
54     1
70     1
58     1
Name: target, dtype: int32

In [36]:
type(x_train)

pandas.core.frame.DataFrame

In [37]:
df_clf = DecisionTreeClassifier(random_state=0)

In [38]:
df_clf

DecisionTreeClassifier(random_state=0)

In [39]:
df_clf.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [40]:
# predict : 답을 안주고 예측시켜보기
pred = df_clf.predict(x_test)

In [41]:
pred

array([0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 1])

In [42]:
y_test

23     0
48     0
0      0
36     0
124    2
9      0
99     1
3      0
38     0
28     0
98     1
132    2
65     1
79     1
43     0
41     0
27     0
139    2
107    2
114    2
6      0
78     1
102    2
29     0
116    2
80     1
72     1
54     1
70     1
58     1
Name: target, dtype: int32

In [43]:
from sklearn.metrics import accuracy_score # 평가와 관련된 것들이 들어있음. 

In [44]:
accuracy_score(y_test, pred)

1.0

In [45]:
def test1(a,b):
    '''
    이 함수는 결과값이 3개로 나갑니다
    '''
    return a+b, a-b, a*b

In [46]:
test1()  # -> shift+tab 하면 위 주석이 나옴

TypeError: test1() missing 2 required positional arguments: 'a' and 'b'

# 과적합 참조
![과적합](다운로드.png)

```
print('hello')
```

In [47]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [48]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [49]:
kfold = KFold(n_splits = 5)  # 명령모드에서 shift+m하면 아래 탭과 합쳐짐, 분리는 명령모드 없이 ctrl+shift+(-)

In [50]:
cv_accuracy=[]

In [51]:
iris.data.shape

(150, 4)

In [52]:
n_iter = 0
for train_index, test_index in kfold.split(iris.data):    # .split 이 인덱스 값을 뽑아줌
#     print(train_index)
#     print("-"*50)
#     print(test_index)
#     print()
    x_train,x_test = iris.data[train_index],iris.data[test_index]
#    print(x_train, x_test)
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = accuracy_score(y_test,pred)   # 정확도
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 : {x_train.shape[0]}, 검증데이터 건수:{x_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:1.0
2번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9666666666666667
3번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.8666666666666667
4번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9333333333333333
5번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.7333333333333333
0.9


In [53]:
kfold = KFold(n_splits = 5, shuffle=True)

In [54]:
cv_accuracy=[]

In [55]:
iris.data.shape

(150, 4)

In [56]:
n_iter = 0
for train_index, test_index in kfold.split(iris.data):    # .split 이 인덱스 값을 뽑아줌
#     print(train_index)
#     print("-"*50)
#     print(test_index)
#     print()
    x_train,x_test = iris.data[train_index],iris.data[test_index]
#    print(x_train, x_test)
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = accuracy_score(y_test,pred)   # 정확도
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 : {x_train.shape[0]}, 검증데이터 건수:{x_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:1.0
2번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9666666666666667
3번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9333333333333333
4번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9666666666666667
5번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9333333333333333
0.9600000000000002


In [57]:
kfold = KFold(n_splits = 5, shuffle=True)

n_iter = 0
for train_index, test_index in kfold.split(iris.data):
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    
    print('학습용데이터 분포:\n', pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n', pd.Series(y_test).value_counts())

학습용데이터 분포:
 2    44
0    39
1    37
dtype: int64
검증용데이터 분포:
 1    13
0    11
2     6
dtype: int64
학습용데이터 분포:
 1    43
0    39
2    38
dtype: int64
검증용데이터 분포:
 2    12
0    11
1     7
dtype: int64
학습용데이터 분포:
 0    43
1    40
2    37
dtype: int64
검증용데이터 분포:
 2    13
1    10
0     7
dtype: int64
학습용데이터 분포:
 1    41
2    40
0    39
dtype: int64
검증용데이터 분포:
 0    11
2    10
1     9
dtype: int64
학습용데이터 분포:
 2    41
0    40
1    39
dtype: int64
검증용데이터 분포:
 1    11
0    10
2     9
dtype: int64


In [58]:
from sklearn.model_selection import StratifiedKFold

In [59]:
kfold = KFold(n_splits = 5, shuffle=False)  # 셔플을 안하게 했는데도 

n_iter = 0
for train_index, test_index in kfold.split(iris.data, iris.target):    # iris.target을 추가함으로써 알아서 비율을 맞췄다
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    
    print('학습용데이터 분포:\n', pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n', pd.Series(y_test).value_counts())

학습용데이터 분포:
 1    50
2    50
0    20
dtype: int64
검증용데이터 분포:
 0    30
dtype: int64
학습용데이터 분포:
 2    50
1    40
0    30
dtype: int64
검증용데이터 분포:
 0    20
1    10
dtype: int64
학습용데이터 분포:
 0    50
2    50
1    20
dtype: int64
검증용데이터 분포:
 1    30
dtype: int64
학습용데이터 분포:
 0    50
1    40
2    30
dtype: int64
검증용데이터 분포:
 2    20
1    10
dtype: int64
학습용데이터 분포:
 0    50
1    50
2    20
dtype: int64
검증용데이터 분포:
 2    30
dtype: int64


In [60]:
skfold = KFold(n_splits = 5, shuffle=True)

n_iter = 0
for train_index, test_index in skfold.split(iris.data, iris.target):
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    
    print('학습용데이터 분포:\n', pd.Series(y_train).value_counts())
    print('검증용데이터 분포:\n', pd.Series(y_test).value_counts())

학습용데이터 분포:
 1    42
0    39
2    39
dtype: int64
검증용데이터 분포:
 0    11
2    11
1     8
dtype: int64
학습용데이터 분포:
 1    43
0    39
2    38
dtype: int64
검증용데이터 분포:
 2    12
0    11
1     7
dtype: int64
학습용데이터 분포:
 0    43
1    40
2    37
dtype: int64
검증용데이터 분포:
 2    13
1    10
0     7
dtype: int64
학습용데이터 분포:
 2    45
0    38
1    37
dtype: int64
검증용데이터 분포:
 1    13
0    12
2     5
dtype: int64
학습용데이터 분포:
 0    41
2    41
1    38
dtype: int64
검증용데이터 분포:
 1    12
0     9
2     9
dtype: int64


In [61]:
skfold = StratifiedKFold(n_splits = 5, shuffle=True)
cv_accuracy = []
n_iter = 0
for train_index, test_index in skfold.split(iris.data, iris.target):    # .split 이 인덱스 값을 뽑아줌
#     print(train_index)
#     print("-"*50)
#     print(test_index)
#     print()
    x_train,x_test = iris.data[train_index],iris.data[test_index]
#    print(x_train, x_test)
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    dt_clf.fit(x_train, y_train)
    pred = dt_clf.predict(x_test)
    accuracy = accuracy_score(y_test,pred)   # 정확도
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 : {x_train.shape[0]}, 검증데이터 건수:{x_test.shape[0]}')
    print(f'정확도:{accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9333333333333333
2번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9666666666666667
3번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9666666666666667
4번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.8666666666666667
5번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수:30
정확도:0.9333333333333333
0.9333333333333333


##### 머신러닝 모델 만들어서 데이터를 나눠넣어 학습, 검증해봄

In [62]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [63]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [66]:
# 교차검증
scores = cross_val_score(dt_clf, 
                        iris_data.data, 
                        iris_data.target, 
                        scoring = "accuracy", 
                        cv=3)
print("교차검증별 정확도", scores)
print("평균 교차검증 정확도", np.mean(scores))

교차검증별 정확도 [0.98 0.94 0.98]
평균 교차검증 정확도 0.9666666666666667


In [68]:
from sklearn.model_selection import GridSearchCV

In [69]:
grid_param = {"max_depth":[1,2,3],
              "min_samples_split":[2,3]}

In [74]:
iris = load_iris()
x_train ,x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()
grid_dtree = GridSearchCV(dtree, param_grid=grid_param, cv=3, refit=True)
grid_dtree.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [75]:
grid_dtree.cv_results_

{'mean_fit_time': array([0.00133061, 0.00066551, 0.0006636 , 0.00066543, 0.00066487,
        0.00133053]),
 'std_fit_time': array([0.00046952, 0.00047058, 0.00046924, 0.00047053, 0.00047013,
        0.00046959]),
 'mean_score_time': array([0.00099659, 0.00033267, 0.00066551, 0.00033259, 0.00099858,
        0.00066296]),
 'std_score_time': array([3.23992047e-06, 4.70471221e-04, 4.70585062e-04, 4.70358829e-04,
        1.99791671e-06, 4.68787328e-04]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'ma

In [76]:
scores_df = pd.DataFrame(grid_dtree.cv_results_)

In [78]:
scores_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [80]:
# 필요한 열만 추출
scores_df[['params', 'mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [81]:
grid_dtree.best_score_

0.975

In [82]:
grid_dtree.best_index_

4

In [84]:
# 학습된 모델
grid_dtree.best_estimator_

DecisionTreeClassifier(max_depth=3)

In [86]:
# 결과값
pred = grid_dtree.best_estimator_.predict(x_test)

In [87]:
# 정확도 체크
print("best estimator 정확도", accuracy_score(y_test, pred))

best estimator 정확도 0.9666666666666667


In [88]:
from sklearn.preprocessing import LabelEncoder

In [89]:
items = ['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [90]:
encoder = LabelEncoder() 
encoder.fit(items)
labels = encoder.transform(items)

In [91]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [92]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [93]:
# 숫자를 다시 문자로 (label encoding)
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

In [94]:
from sklearn.preprocessing import OneHotEncoder

In [95]:
# 한번에 변환하기
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [99]:
labels.shape # 1차원임. 이렇게 하면 오류남
labels = labels.reshape(1,-1) # 차원 바꿔주기
labels.shape

(1, 8)

In [110]:
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

In [113]:
oh_encoder.categories_

[array([0], dtype=int64),
 array([1], dtype=int64),
 array([4], dtype=int64),
 array([5], dtype=int64),
 array([3], dtype=int64),
 array([3], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64)]

In [115]:
oh_encoder.sparse

True

In [119]:
oh_labels.toarray()

array([[1., 1., 1., 1., 1., 1., 1., 1.]])

In [118]:
oh_labels.data

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
# 원핫인코딩보다 밑의 판다스를 사용한게 더 수월함
df = pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})

In [122]:
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [124]:
pd.get_dummies(df).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)